# Generated by Django 3.2.10 on 2023-04-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
