# Generated by Django 3.2.10 on 2023-04-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='price',
        ),
    ]
