# Generated by Django 3.2.10 on 2023-04-10 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserve', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='money',
            field=models.ForeignKey(default=1, help_text='Баланс пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.users'),
            preserve_default=False,
        ),
    ]
