# Generated by Django 3.2.10 on 2023-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_remove_reserve_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='new_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
