# Generated by Django 3.2.10 on 2023-04-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_balance_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
