# Generated by Django 3.2.10 on 2023-04-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reserve_new_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='reserve.order'),
            preserve_default=False,
        ),
    ]
