# Generated by Django 3.2.10 on 2023-04-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_reserve_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='new_balance',
            new_name='reserve_balance',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='orders',
        ),
    ]
