# Generated by Django 3.2.10 on 2023-04-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
