# Generated by Django 3.2.10 on 2023-04-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20230416_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='service',
        ),
    ]
