# Generated by Django 3.2.10 on 2023-04-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_remove_revenue_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='order',
        ),
    ]
