# Generated by Django 3.2.10 on 2023-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_order_orderusers_service_serviceuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Услуги'},
        ),
    ]
