# Generated by Django 3.2.10 on 2023-04-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_remove_revenue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='reserve.order'),
            preserve_default=False,
        ),
    ]
