# Generated by Django 3.2.10 on 2023-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_revenue_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='order',
        ),
        migrations.AddField(
            model_name='revenue',
            name='order',
            field=models.ManyToManyField(related_name='revenue', to='reserve.Order'),
        ),
    ]
