# Generated by Django 3.2.10 on 2023-04-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_auto_20230412_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(related_name='order', to='reserve.Service'),
        ),
        migrations.DeleteModel(
            name='ServiceUser',
        ),
    ]
