# Generated by Django 3.2.10 on 2023-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20230416_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='service',
            field=models.ManyToManyField(related_name='revenue', to='reserve.Service'),
        ),
    ]
