# Generated by Django 3.2.10 on 2023-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_revenue_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='services',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
