# Generated by Django 3.2.10 on 2023-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_revenue_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='services',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='service',
        ),
        migrations.AddField(
            model_name='revenue',
            name='service',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
