# Generated by Django 3.2.10 on 2023-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_serviceuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(related_name='order', to='reserve.Service'),
        ),
    ]
