# Generated by Django 3.2.10 on 2023-04-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0015_auto_20230413_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='service',
        ),
        migrations.DeleteModel(
            name='OrderUsers',
        ),
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
