# Generated by Django 3.2.10 on 2023-04-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
