# Generated by Django 3.2.10 on 2023-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=1, verbose_name='Итого'),
            preserve_default=False,
        ),
    ]
