# Generated by Django 3.2.10 on 2023-04-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='balance',
        ),
    ]
