# Generated by Django 3.2.10 on 2023-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_users_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.PositiveIntegerField(default=1, help_text='Баланс пользователя'),
            preserve_default=False,
        ),
    ]
