# Generated by Django 3.2.10 on 2023-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Баланс пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(help_text='Введите вашу почту', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(help_text='Введите ваше имя', max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(help_text='Введите вашу фамилию', max_length=150, verbose_name='Фамилия пользователя'),
        ),
    ]
