# Generated by Django 3.2.10 on 2023-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230410_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс пользователя'),
        ),
    ]
